name: Build Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      # هذا هو السطر الجديد اللي بيحل المشكلة
      - name: Install Dependencies
        run: brew install ldid

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
          
      - name: Build Tweak
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          export PATH=$THEOS/bin:$PATH
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TikTokSpoof-Deb
          path: packages/*.deb
